#include<iostream.h>
#include<conio.h>
#include<string.h>
void main()
{
char a[100],cho1[100],sc[5];
int l;
clrscr();
endl;endl;endl;
cout<<"COPYRIGHT 1980-2016 DX"<<endl;
cout<<"            Loading..."<<endl;
endl;
cout<<"1.Loading Components..."<<endl;
cout<<"2.Loading Menu..."<<endl;
cout<<"3.Connecting To DX Server_INDIA..."<<endl;
cout<<"4.CONNECTED."<<endl;
cout<<"Successfully Loaded!!!"<<endl;
cout<<".:!PRESS ANY KEY TO CONTINUE!:.";
getch();
clrscr();
cout<<"----BANKER----v1.0"<<endl;
cout<<"Welcome,"<<endl;
cout<<"Please enter your First Name(WARNING: THIS NAME WILL BE DISPLAYED THROUGHOUT THE TRANSACTION) : ";
cin>>a;
clrscr();
cout<<"----BANKER----v1.0"<<endl;
cout<<"Welcome "<<cho1<<","<<endl;
cout<<"Tips: 1. NEVER SHARE YOUR BANK NOS. WITH ANYONE!!!"<<endl;
cout<<"      2. Before entering your SECRET NO., check that no one is peeping at you..."<<endl;
cout<<"NOTE: This carrier company isn't responsible if your bank identity is stolen by someone."<<endl;
endl;
endl;
cout<<"PLEASE ENTER ANY KEY TO PROCEED...";
getch();
do
{
clrscr();
cout<<"Please enter your SECRET no. : "<<endl;
cin>>sc;
l=StrLen(sc);
}
while(scl=0||scl>4)
getch();
}